### PR TITLE
transaction history

### PR DESCRIPTION
**Pull request by ltminhthu**

### CODE REVIEW

**Comment by tanlethanh** [comment]
@ltminhthu I fixed `getSolanaMetadata` to get correct `imageUrl` instead of `json` uri

**Comment by tanlethanh** [comment]
@ltminhthu please push code if there is anything new

**Comment by ltminhthu** [comment]
> @ltminhthu please push code if there is anything new
You can check, I've just pushed it

**Comment by ltminhthu** [comment]
> @ltminhthu please push code if there is anything new

You can check, I've just pushed it

**Review by fluctlight-kayaba — APPROVED** [review]

**Pull request merged**
